### ISSUE TITLE
Corrupted vex format

### ISSUE THREAD

**Issue by mattwigway** [conveyal/osm-lib#13]
When I retrieve http://osm.conveyal.com/vex/42.3744,-71.0789,42.3892,-71.0505.vex and then try to read it, I get:

```
Exception in thread "Thread-1" java.lang.RuntimeException: Block has impossible compressed data size, it is probably corrupted.
    at com.conveyal.osmlib.VEXBlock.readHeader(VEXBlock.java:85)
    at com.conveyal.osmlib.VEXBlock.readDeflated(VEXBlock.java:41)
    at com.conveyal.osmlib.DeflatedBlockReader.run(DeflatedBlockReader.java:56)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by mattwigway** [comment]
The PBF output appears to be corrupted as well. I see a lot of these in the server logs:

`15:19:51.672 ERROR (TileOSMSource.java:65) Way 323161778 is not available.`

**Comment by mattwigway** [comment]
This was operator error, reading with the wrong version of the protobuf dependency.
